### ISSUE TITLE
Adição de membros na organization

### ISSUE THREAD

**Issue by oviniciusfeitosa** [php-df/internals#20]
Eu como membro do PHPDF Internals solicito que seja **deixado um comentário nessa Issue** para usuários que fazem parte da comunidade PHPDF porém ainda não estão na nossa Organization no Github como Membros. Dessa forma poderemos enviar convites para entrar.

**Comment by phackwer** [comment]
Yo

**Comment by cleitonsb** [comment]
Up

**Comment by luanhenriquepp** [comment]
Hi

**Comment by leandroreis** [comment]
:)

**Comment by dougs007** [comment]
\*..\*

**Comment by flmendes** [comment]
Ping.

**Comment by solbisio** [comment]
opa

**Comment by celorodovalho** [comment]
Me

**Comment by Dhayllin** [comment]
Opaa

**Comment by franklinfarias** [comment]
Add

**Comment by bc05** [comment]
Yo
